### ISSUE TITLE
Bug in aep8

### ISSUE THREAD

**Issue by jacobwilliams** [nasa/radbelt#73]
https://github.com/nasa/radbelt/blob/75fbf407b5a62faaa152d6f8d819cca43cf38675/radbelt/core.f#L50

This `IER` in `AEP8` should be `IERR`. IER is never given a value, so it can be anything.

**Comment by lpsinger** [comment]
I'm not much of a FORTRAN programmer. Is it also a problem that IERR is not defined?

**Comment by jacobwilliams** [comment]
IERR was an integer (since the Fortran implicit typing rules are in effect since this function doesn't have `implicit none`), and given a value by the OPEN call, so that was fine. It doesn't hurt to explicitly define it as you have done.
